# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='nome')),
                ('last_name', models.CharField(max_length=45, verbose_name='sobrenome')),
                ('status', models.IntegerField(verbose_name='status')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
    ]
